  // Travail fait par :
//   NomEquipier1 - Matricule
//   NomEquipier2 - Matricule

package tp1;

import org.json.JSONObject;
import org.json.XML;

/**
 * Fichier de base pour le Devoir1A du cours IFT287
 * <pre>
 * 
 * Vincent Ducharme
 * Universite de Sherbrooke
 * Version 1.0 - 6 août 2016
 * IFT287 - Exploitation de BD relationnelles et OO
 * 
 * Ce programme permet de convertir un fichier XML en son équivalent en JSON.
 *
 * Paramètres du programme
 * 0- Nom du fichier XML
 * 1- Nom du fichier JSON
 * 
 * </pre>
 */
public class Devoir1A
{
	 private static final int PRETTY_PRINT_INDENT_FACTOR = 4;

    public static void main(String[] args)
    {
    	
    	
    	  String xmlString = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n"
    	  		+ "<!DOCTYPE MainBody SYSTEM \"HumanBody.dtd\">\r\n"
    	  		+ "<MainBody bodyName=\"DrHouse\" bodyID=\"1\">\r\n"
    	  		+ "  <Systems>\r\n"
    	  		+ "    <!--Type for system are :\r\n"
    	  		+ "      0 : Circulatory system\r\n"
    	  		+ "      1 : Respiratory system\r\n"
    	  		+ "      2 : Digestive system\r\n"
    	  		+ "      3 : Urinary system\r\n"
    	  		+ "      4 : Endocrine system\r\n"
    	  		+ "      5 : Nervous system\r\n"
    	  		+ "      6 : Skeletal system\r\n"
    	  		+ "      7 : Muscular system\r\n"
    	  		+ "      -->\r\n"
    	  		+ "    <!--Circulatory system-->\r\n"
    	  		+ "    <System name=\"Circulatory\" id=\"0\" type=\"0\">\r\n"
    	  		+ "      <!--Heart flow-->\r\n"
    	  		+ "      <Flow id=\"0\" name=\"Heart\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Atrium    name=\"Left atrium\"     id=\"0\" volume=\"120.0\"/>\r\n"
    	  		+ "          <Atrium    name=\"Right atrium\"    id=\"1\" volume=\"120.0\"/>\r\n"
    	  		+ "          <Ventricle name=\"Left ventricle\"  id=\"2\" volume=\"120.0\"/>\r\n"
    	  		+ "          <Ventricle name=\"Right ventricle\" id=\"3\" volume=\"120.0\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Aorta flow-->\r\n"
    	  		+ "      <Flow id=\"1\" name=\"Aorta connection\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Ascending aorta\"    id=\"0\" startRadius=\"1.3\" endRadius=\"1.4\" length=\"3\"/>\r\n"
    	  		+ "          <Artery name=\"Arch of the aorta\"  id=\"1\" startRadius=\"1.4\" endRadius=\"1.6\" length=\"3\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Coronary flow-->\r\n"
    	  		+ "      <Flow id=\"2\" name=\"Coronary\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Left coronary\"               id=\"0\" startRadius=\"0.271109\" endRadius=\"0.271109\" length=\"4\"/>\r\n"
    	  		+ "          <Artery name=\"Right coronary\"              id=\"1\" startRadius=\"0.156525\" endRadius=\"0.156525\" length=\"4\"/>\r\n"
    	  		+ "          <Artery name=\"Posterior inter ventricular\" id=\"2\" startRadius=\"0.156525\" endRadius=\"0.156525\" length=\"3\"/>\r\n"
    	  		+ "          <Artery name=\"Anterior inter ventricular\"  id=\"3\" startRadius=\"0.191703\" endRadius=\"0.191703\" length=\"3\"/>\r\n"
    	  		+ "          <Artery name=\"Circumflex\"                  id=\"4\" startRadius=\"0.191703\" endRadius=\"0.191703\" length=\"3\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Middle cardiac\"     id=\"5\"  startRadius=\"0.271109\" endRadius=\"0.271109\" length=\"6\"/>\r\n"
    	  		+ "          <Vein name=\"Great cardiac\"      id=\"6\"  startRadius=\"0.271109\" endRadius=\"0.271109\" length=\"6\"/>\r\n"
    	  		+ "          <Vein name=\"Anterior cardiac\"   id=\"7\"  startRadius=\"0.156525\" endRadius=\"0.156525\" length=\"3\"/>\r\n"
    	  		+ "          <Vein name=\"Small cardiac\"      id=\"8\"  startRadius=\"0.156525\" endRadius=\"0.156525\" length=\"3\"/>\r\n"
    	  		+ "          <Vein name=\"Great anterior\"     id=\"9\"  startRadius=\"0.221360\" endRadius=\"0.221360\" length=\"3\"/>\r\n"
    	  		+ "          <Vein name=\"Coronary sinus\"     id=\"10\" startRadius=\"0.313049\" endRadius=\"0.313049\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Capillaries name=\"Left heart\"  id=\"11\" volume=\"100.0\"/>\r\n"
    	  		+ "          <Capillaries name=\"Right heart\" id=\"12\" volume=\"100.0\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"11\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"12\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Pulmonary flow-->\r\n"
    	  		+ "      <Flow id=\"3\" name=\"Pulmonary\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Pulmonary trunk\"  id=\"0\" startRadius=\"1.5\" endRadius=\"1.5\"  length=\"6\"/>\r\n"
    	  		+ "          <Artery name=\"Right pulmonary\"  id=\"1\" startRadius=\"1.06060\" length=\"6\"/>\r\n"
    	  		+ "          <Artery name=\"Left pulmonary\"   id=\"2\" startRadius=\"1.06060\" length=\"6\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Right pulmonary 1\"  id=\"3\" startRadius=\"1.06060\" length=\"7\"/>\r\n"
    	  		+ "          <Vein name=\"Right pulmonary 2\"  id=\"4\" startRadius=\"1.06060\" length=\"7\"/>\r\n"
    	  		+ "          <Vein name=\"Left pulmonary 1\"   id=\"5\" startRadius=\"1.06060\" length=\"7\"/>\r\n"
    	  		+ "          <Vein name=\"Left pulmonary 2\"   id=\"6\" startRadius=\"1.06060\" length=\"7\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Capillaries name=\"Left alveoli\"  id=\"7\" volume=\"120.0\"/>\r\n"
    	  		+ "          <Capillaries name=\"Right alveoli\" id=\"8\" volume=\"120.0\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"2\">\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--3,4,5,6 are connected to the heart flow-->\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Head and thoracic-->\r\n"
    	  		+ "      <Flow id=\"4\" name=\"Head and thoracic\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Left subclavian\"      id=\"0\" startRadius=\"0.15\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left common carotid\"  id=\"1\" startRadius=\"0.075\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Brachiocephalic\"      id=\"2\" startRadius=\"0.225\" length=\"2.25\"/>\r\n"
    	  		+ "          <Artery name=\"Thoracic aorta\"       id=\"3\" startRadius=\"1.25\"  length=\"13\"/>\r\n"
    	  		+ "          <Artery name=\"Right subclavian\"     id=\"4\" startRadius=\"0.15\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right common carotid\" id=\"5\" startRadius=\"0.075\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Artery name=\"Right internal thoracic\"      id=\"6\" startRadius=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right posterior intercostal\"  id=\"7\" startRadius=\"0.01\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right vertebral\"              id=\"8\" startRadius=\"0.03\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Artery name=\"Left internal thoracic\"     id=\"9\"  startRadius=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left posterior intercostal\" id=\"10\" startRadius=\"0.01\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left vertebral\"             id=\"11\" startRadius=\"0.03\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Artery name=\"Basilar\"                id=\"12\" startRadius=\"0.04\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right internal carotid\" id=\"13\" startRadius=\"0.03\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left internal carotid\"  id=\"14\" startRadius=\"0.03\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Artery name=\"Right superior thyroid\" id=\"15\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left superior thyroid\"  id=\"16\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right facial\"           id=\"17\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left facial\"            id=\"18\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right lingual\"          id=\"19\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left lingual\"           id=\"20\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Artery name=\"Right external carotid\"     id=\"21\" startRadius=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left external carotid\"      id=\"22\" startRadius=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right superficial temporal\" id=\"23\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left superficial temporal\"  id=\"24\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right maxillary\"            id=\"25\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left maxillary\"             id=\"26\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right occipital\"            id=\"27\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left occipital\"             id=\"28\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Artery name=\"Bronchial\"                id=\"29\" startRadius=\"0.01\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Esophageal\"               id=\"30\" startRadius=\"0.01\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right superior phrenic\"   id=\"31\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left superior phrenic\"    id=\"32\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Right superior thyroid\"     id=\"33\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left superior thyroid\"      id=\"34\" startRadius=\"0.005\" length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right internal jugular\"     id=\"35\" startRadius=\"0.055\" length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left internal jugular\"      id=\"36\" startRadius=\"0.055\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Right facial\"               id=\"37\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left facial\"                id=\"38\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right lingual\"              id=\"39\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left lingual\"               id=\"40\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right occipital\"            id=\"41\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left occipital\"             id=\"42\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right superficial temporal\" id=\"43\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left superficial temporal\"  id=\"44\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right maxillary\"            id=\"45\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left maxillary\"             id=\"46\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right external jugular\"     id=\"47\" startRadius=\"0.04\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left external jugular\"      id=\"48\" startRadius=\"0.04\"   length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Right internal thoracic\"  id=\"49\" startRadius=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left internal thoracic\"   id=\"50\" startRadius=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right vertebral\"          id=\"51\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left vertebral\"           id=\"52\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Azygos\"                   id=\"53\" startRadius=\"0.055\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Hemiazygos\"               id=\"54\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Bronchial\"                id=\"55\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Esophageal\"               id=\"56\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Pericardial\"              id=\"57\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Right brachiocephalic\"  id=\"58\" startRadius=\"0.205\" length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left brachiocephalic\"   id=\"59\" startRadius=\"0.205\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Capillaries name=\"Brain\"         id=\"60\" volume=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Thyroid\"       id=\"61\" volume=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Facial\"        id=\"62\" volume=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Lingual\"       id=\"63\" volume=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Head\"          id=\"64\" volume=\"0.05\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Maxilary\"      id=\"65\" volume=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Vertebral\"     id=\"66\" volume=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Right costal\"  id=\"67\" volume=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Left costal\"   id=\"68\" volume=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Lung\"          id=\"69\" volume=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Esophageal\"    id=\"70\" volume=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Diaphragm\"     id=\"71\" volume=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "            <to id=\"16\"/>\r\n"
    	  		+ "            <to id=\"18\"/>\r\n"
    	  		+ "            <to id=\"20\"/>\r\n"
    	  		+ "            <to id=\"22\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"2\">\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"3\">\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "            <to id=\"29\"/>\r\n"
    	  		+ "            <to id=\"30\"/>\r\n"
    	  		+ "            <to id=\"31\"/>\r\n"
    	  		+ "            <to id=\"32\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"4\">\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"5\">\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "            <to id=\"17\"/>\r\n"
    	  		+ "            <to id=\"19\"/>\r\n"
    	  		+ "            <to id=\"21\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"6\">\r\n"
    	  		+ "            <to id=\"67\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"67\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "            <to id=\"66\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"9\">\r\n"
    	  		+ "            <to id=\"68\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"10\">\r\n"
    	  		+ "            <to id=\"68\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"11\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "            <to id=\"66\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"12\">\r\n"
    	  		+ "            <to id=\"60\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"13\">\r\n"
    	  		+ "            <to id=\"60\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"14\">\r\n"
    	  		+ "            <to id=\"60\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"15\">\r\n"
    	  		+ "            <to id=\"61\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"16\">\r\n"
    	  		+ "            <to id=\"61\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"17\">\r\n"
    	  		+ "            <to id=\"62\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"18\">\r\n"
    	  		+ "            <to id=\"62\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"19\">\r\n"
    	  		+ "            <to id=\"63\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"20\">\r\n"
    	  		+ "            <to id=\"63\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"21\">\r\n"
    	  		+ "            <to id=\"23\"/>\r\n"
    	  		+ "            <to id=\"27\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"22\">\r\n"
    	  		+ "            <to id=\"24\"/>\r\n"
    	  		+ "            <to id=\"28\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"23\">\r\n"
    	  		+ "            <to id=\"25\"/>\r\n"
    	  		+ "            <to id=\"64\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"24\">\r\n"
    	  		+ "            <to id=\"26\"/>\r\n"
    	  		+ "            <to id=\"64\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"25\">\r\n"
    	  		+ "            <to id=\"65\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"26\">\r\n"
    	  		+ "            <to id=\"65\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"27\">\r\n"
    	  		+ "            <to id=\"64\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"28\">\r\n"
    	  		+ "            <to id=\"64\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"29\">\r\n"
    	  		+ "            <to id=\"69\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"30\">\r\n"
    	  		+ "            <to id=\"70\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"31\">\r\n"
    	  		+ "            <to id=\"71\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"32\">\r\n"
    	  		+ "            <to id=\"71\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"33\">\r\n"
    	  		+ "            <to id=\"35\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"34\">\r\n"
    	  		+ "            <to id=\"36\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"35\">\r\n"
    	  		+ "            <to id=\"58\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"36\">\r\n"
    	  		+ "            <to id=\"59\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"37\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"38\">\r\n"
    	  		+ "            <to id=\"48\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"39\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"40\">\r\n"
    	  		+ "            <to id=\"48\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"41\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"42\">\r\n"
    	  		+ "            <to id=\"48\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"43\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"44\">\r\n"
    	  		+ "            <to id=\"48\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"45\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"46\">\r\n"
    	  		+ "            <to id=\"48\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"47\">\r\n"
    	  		+ "            <to id=\"58\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"48\">\r\n"
    	  		+ "            <to id=\"59\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--49 connect directly to superior vena cava-->\r\n"
    	  		+ "          <!--50 connect directly to superior vena cava-->\r\n"
    	  		+ "          <Connection id=\"51\">\r\n"
    	  		+ "            <to id=\"58\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"52\">\r\n"
    	  		+ "            <to id=\"59\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--53 connect direclty to superior vena cava-->\r\n"
    	  		+ "          <Connection id=\"54\">\r\n"
    	  		+ "            <to id=\"53\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"55\">\r\n"
    	  		+ "            <to id=\"53\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"56\">\r\n"
    	  		+ "            <to id=\"53\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"57\">\r\n"
    	  		+ "            <to id=\"53\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--58 connect directly to superior vena cava-->\r\n"
    	  		+ "          <!--59 connect directly to superior vena cava-->\r\n"
    	  		+ "          <Connection id=\"60\">\r\n"
    	  		+ "            <to id=\"35\"/>\r\n"
    	  		+ "            <to id=\"36\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"61\">\r\n"
    	  		+ "            <to id=\"33\"/>\r\n"
    	  		+ "            <to id=\"34\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"62\">\r\n"
    	  		+ "            <to id=\"37\"/>\r\n"
    	  		+ "            <to id=\"38\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"63\">\r\n"
    	  		+ "            <to id=\"39\"/>\r\n"
    	  		+ "            <to id=\"40\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"64\">\r\n"
    	  		+ "            <to id=\"41\"/>\r\n"
    	  		+ "            <to id=\"42\"/>\r\n"
    	  		+ "            <to id=\"43\"/>\r\n"
    	  		+ "            <to id=\"44\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"65\">\r\n"
    	  		+ "            <to id=\"45\"/>\r\n"
    	  		+ "            <to id=\"46\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"66\">\r\n"
    	  		+ "            <to id=\"51\"/>\r\n"
    	  		+ "            <to id=\"52\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"67\">\r\n"
    	  		+ "            <to id=\"49\"/>\r\n"
    	  		+ "            <to id=\"53\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"68\">\r\n"
    	  		+ "            <to id=\"50\"/>\r\n"
    	  		+ "            <to id=\"54\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"69\">\r\n"
    	  		+ "            <to id=\"55\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"70\">\r\n"
    	  		+ "            <to id=\"56\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"71\">\r\n"
    	  		+ "            <to id=\"57\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Left arm-->\r\n"
    	  		+ "      <Flow id=\"5\" name=\"Left arm\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Axillary\"                 id=\"0\" startRadius=\"0.1\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Brachial\"                 id=\"1\" startRadius=\"0.08\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Radial\"                   id=\"2\" startRadius=\"0.03\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Ulnar\"                    id=\"3\" startRadius=\"0.03\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Deep palmar arch\"         id=\"4\" startRadius=\"0.02\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Superficial palmar arch\"  id=\"5\" startRadius=\"0.02\"  length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Basilic\"    id=\"6\"  startRadius=\"0.035\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Cephalic\"   id=\"7\"  startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Ulnar\"      id=\"8\"  startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Radial\"     id=\"9\"  startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Brachial\"   id=\"10\" startRadius=\"0.045\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Axillary\"   id=\"11\" startRadius=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Subclavian\" id=\"12\" startRadius=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Capillaries name=\"Upper arm\" id=\"13\" volume=\"0.04\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Lower arm\" id=\"14\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Digital\"   id=\"15\" volume=\"0.04\" length=\"1\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"2\">\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"3\">\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"4\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"5\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"6\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"9\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"10\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"11\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--12 connect directly to left brachiocephalic-->\r\n"
    	  		+ "          <Connection id=\"13\">\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"14\">\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"15\">\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Right arm-->\r\n"
    	  		+ "      <Flow id=\"6\" name=\"Right arm\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Axillary\"                 id=\"0\" startRadius=\"0.1\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Brachial\"                 id=\"1\" startRadius=\"0.08\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Radial\"                   id=\"2\" startRadius=\"0.03\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Ulnar\"                    id=\"3\" startRadius=\"0.03\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Deep palmar arch\"         id=\"4\" startRadius=\"0.02\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Superficial palmar arch\"  id=\"5\" startRadius=\"0.02\"  length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Basilic\"    id=\"6\"  startRadius=\"0.035\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Cephalic\"   id=\"7\"  startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Ulnar\"      id=\"8\"  startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Radial\"     id=\"9\"  startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Brachial\"   id=\"10\" startRadius=\"0.045\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Axillary\"   id=\"11\" startRadius=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Subclavian\" id=\"12\" startRadius=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Capillaries name=\"Upper arm\" id=\"13\" volume=\"0.04\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Lower arm\" id=\"14\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Digital\"   id=\"15\" volume=\"0.04\" length=\"1\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"2\">\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"3\">\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"4\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"5\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"6\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"9\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"10\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"11\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--12 connect directly to left brachiocephalic-->\r\n"
    	  		+ "          <Connection id=\"13\">\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"14\">\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"15\">\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Abdominal-->\r\n"
    	  		+ "      <Flow id=\"7\" name=\"Abdominal\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Abdominal aorta\"        id=\"0\" startRadius=\"1.20\" endRadius=\"0.875\"    length=\"25\"/>\r\n"
    	  		+ "          <Artery name=\"Right inferior phrenic\" id=\"1\" startRadius=\"0.0025\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left inferior phrenic\"  id=\"2\" startRadius=\"0.0025\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right suprarenal\"       id=\"3\" startRadius=\"0.005\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left suprarenal\"        id=\"4\" startRadius=\"0.005\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Lumbar\"                 id=\"5\" startRadius=\"0.01\"    length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right renal\"            id=\"6\" startRadius=\"0.025\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left renal\"             id=\"7\" startRadius=\"0.025\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Superior mesenteric\"    id=\"8\" startRadius=\"0.055\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Inferior mesenteric\"    id=\"9\" startRadius=\"0.03\"    length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right gonad\"            id=\"10\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left gonad\"             id=\"11\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Celiac trunk\"           id=\"12\" startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Hepatic\"                id=\"13\" startRadius=\"0.045\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Splenic\"                id=\"14\" startRadius=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left gastric\"           id=\"15\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Gastroduodenal\"         id=\"16\" startRadius=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right gastric\"          id=\"17\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Right gastroepiploic\"   id=\"18\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Left gastroepiploic\"    id=\"19\" startRadius=\"0.0025\" length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Right suprarenal\"         id=\"20\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left suprarenal\"          id=\"21\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Lumbar\"                   id=\"22\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right renal\"              id=\"23\" startRadius=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left renal\"               id=\"24\" startRadius=\"0.035\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Right gonad\"              id=\"25\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Left gonad\"               id=\"26\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Inferior mesenteric\"      id=\"27\" startRadius=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Superior mesenteric\"      id=\"28\" startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Gastric\"                  id=\"29\" startRadius=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Gastroepiploic\"           id=\"30\" startRadius=\"0.0025\" length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Hepatic portal\"           id=\"31\" startRadius=\"0.135\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Hepatic\"                  id=\"32\" startRadius=\"0.165\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Splenic\"                  id=\"33\" startRadius=\"0.05\"   length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Capillaries name=\"Right adrenal gland\"       id=\"34\" volume=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Left adrenal gland\"        id=\"35\" volume=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Right reproductive gonad\"  id=\"36\" volume=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Left reproductive gonad\"   id=\"37\" volume=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Right renal\"               id=\"38\" volume=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Left renal\"                id=\"39\" volume=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Lumbar vertebra\"           id=\"40\" volume=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Intestinal\"                id=\"41\" volume=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Transverse colon\"          id=\"42\" volume=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Ascending colon\"           id=\"43\" volume=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Gallbladder\"               id=\"44\" volume=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Descending colon\"          id=\"45\" volume=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Sigmoid colon\"             id=\"46\" volume=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Stomach\"                   id=\"47\" volume=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Pancreas\"                  id=\"48\" volume=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Spleen\"                    id=\"49\" volume=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Liver inner system\"        id=\"50\" volume=\"0.165\"  length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Liver\"                     id=\"51\" volume=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Duodenum\"                  id=\"52\" volume=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Common gastroduodenal\"     id=\"53\" volume=\"0.035\"  length=\"1\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--1,2 connect directly to the diaphragm capillaries in Head thoracic flow-->\r\n"
    	  		+ "          <Connection id=\"3\">\r\n"
    	  		+ "            <to id=\"34\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"4\">\r\n"
    	  		+ "            <to id=\"35\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"5\">\r\n"
    	  		+ "            <to id=\"40\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"6\">\r\n"
    	  		+ "            <to id=\"38\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"39\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"41\"/>\r\n"
    	  		+ "            <to id=\"42\"/>\r\n"
    	  		+ "            <to id=\"43\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"9\">\r\n"
    	  		+ "            <to id=\"45\"/>\r\n"
    	  		+ "            <to id=\"46\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"10\">\r\n"
    	  		+ "            <to id=\"36\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"11\">\r\n"
    	  		+ "            <to id=\"37\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"12\">\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"13\">\r\n"
    	  		+ "            <to id=\"16\"/>\r\n"
    	  		+ "            <to id=\"17\"/>\r\n"
    	  		+ "            <to id=\"51\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"14\">\r\n"
    	  		+ "            <to id=\"19\"/>\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "            <to id=\"48\"/>\r\n"
    	  		+ "            <to id=\"49\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"15\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"16\">\r\n"
    	  		+ "            <to id=\"18\"/>\r\n"
    	  		+ "            <to id=\"48\"/>\r\n"
    	  		+ "            <to id=\"52\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"17\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"18\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"19\">\r\n"
    	  		+ "            <to id=\"47\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--20 connect directly to inf vena cava-->\r\n"
    	  		+ "          <Connection id=\"21\">\r\n"
    	  		+ "            <to id=\"24\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--22,23,24,25 connect directly to inf vena cava-->\r\n"
    	  		+ "          <Connection id=\"26\">\r\n"
    	  		+ "            <to id=\"24\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"27\">\r\n"
    	  		+ "            <to id=\"33\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"28\">\r\n"
    	  		+ "            <to id=\"31\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"29\">\r\n"
    	  		+ "            <to id=\"28\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"30\">\r\n"
    	  		+ "            <to id=\"29\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"31\">\r\n"
    	  		+ "            <to id=\"50\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--32 connect directly to inf vena cava-->\r\n"
    	  		+ "          <Connection id=\"33\">\r\n"
    	  		+ "            <to id=\"31\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"34\">\r\n"
    	  		+ "            <to id=\"20\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"35\">\r\n"
    	  		+ "            <to id=\"21\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"36\">\r\n"
    	  		+ "            <to id=\"25\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"37\">\r\n"
    	  		+ "            <to id=\"26\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"38\">\r\n"
    	  		+ "            <to id=\"23\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"39\">\r\n"
    	  		+ "            <to id=\"24\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"40\">\r\n"
    	  		+ "            <to id=\"22\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"41\">\r\n"
    	  		+ "            <to id=\"28\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"42\">\r\n"
    	  		+ "            <to id=\"28\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"43\">\r\n"
    	  		+ "            <to id=\"28\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"44\">\r\n"
    	  		+ "            <to id=\"31\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"45\">\r\n"
    	  		+ "            <to id=\"27\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"46\">\r\n"
    	  		+ "            <to id=\"27\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"47\">\r\n"
    	  		+ "            <to id=\"29\"/>\r\n"
    	  		+ "            <to id=\"30\"/>\r\n"
    	  		+ "            <to id=\"53\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"48\">\r\n"
    	  		+ "            <to id=\"33\"/>\r\n"
    	  		+ "            <to id=\"53\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"49\">\r\n"
    	  		+ "            <to id=\"33\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"50\">\r\n"
    	  		+ "            <to id=\"32\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"51\">\r\n"
    	  		+ "            <to id=\"50\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"52\">\r\n"
    	  		+ "            <to id=\"44\"/>\r\n"
    	  		+ "            <to id=\"53\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"53\">\r\n"
    	  		+ "            <to id=\"29\"/>\r\n"
    	  		+ "            <to id=\"51\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Right leg-->\r\n"
    	  		+ "      <Flow id=\"8\" name=\"Right leg\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Common Iliac\"     id=\"0\"  startRadius=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"External Iliac\"   id=\"1\"  startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Internal Iliac\"   id=\"2\"  startRadius=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Femoral\"          id=\"3\"  startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Popliteal\"        id=\"4\"  startRadius=\"0.06\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Anterior Tibial\"  id=\"5\"  startRadius=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Posterior Tibial\" id=\"6\"  startRadius=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Dorsalis Pedis\"   id=\"7\"  startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Lateral Plantar\"  id=\"8\"  startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Peroneal\"         id=\"9\"  startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Medial Plantar\"   id=\"10\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Plantar Arch\"     id=\"11\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Common Iliac\"       id=\"12\" startRadius=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"External Iliac\"     id=\"13\" startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Internal Iliac\"     id=\"14\" startRadius=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Femoral\"            id=\"15\" startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Popliteal\"          id=\"16\" startRadius=\"0.045\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Anterior Tibial\"    id=\"17\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Great Saphenous\"    id=\"18\" startRadius=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Small Saphenous\"    id=\"19\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Posterior Tibial\"   id=\"20\" startRadius=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Peroneal\"           id=\"21\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Dorsal Venous Arch\" id=\"22\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Capillaries name=\"Thight\"            id=\"23\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Anterior Leg\"      id=\"24\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Posterior Tibial\"  id=\"25\" volume=\"0.01\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Peroneal\"          id=\"26\" volume=\"0.01\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Digital\"           id=\"27\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Pelvic\"            id=\"28\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"2\">\r\n"
    	  		+ "            <to id=\"28\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"3\">\r\n"
    	  		+ "            <to id=\"23\"/>\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"4\">\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"5\">\r\n"
    	  		+ "            <to id=\"24\"/>\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"6\">\r\n"
    	  		+ "            <to id=\"25\"/>\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"27\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"9\">\r\n"
    	  		+ "            <to id=\"26\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"10\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"11\">\r\n"
    	  		+ "            <to id=\"27\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--12 connect directly to inferior vena cava-->\r\n"
    	  		+ "          <Connection id=\"13\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"14\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"15\">\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"16\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"17\">\r\n"
    	  		+ "            <to id=\"16\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"18\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"19\">\r\n"
    	  		+ "            <to id=\"16\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"20\">\r\n"
    	  		+ "            <to id=\"16\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"21\">\r\n"
    	  		+ "            <to id=\"20\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"22\">\r\n"
    	  		+ "            <to id=\"17\"/>\r\n"
    	  		+ "            <to id=\"18\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"23\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "            <to id=\"18\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"24\">\r\n"
    	  		+ "            <to id=\"17\"/>\r\n"
    	  		+ "            <to id=\"18\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"25\">\r\n"
    	  		+ "            <to id=\"20\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"26\">\r\n"
    	  		+ "            <to id=\"19\"/>\r\n"
    	  		+ "            <to id=\"21\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"27\">\r\n"
    	  		+ "            <to id=\"19\"/>\r\n"
    	  		+ "            <to id=\"20\"/>\r\n"
    	  		+ "            <to id=\"22\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"28\">\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Left leg-->\r\n"
    	  		+ "      <Flow id=\"9\" name=\"Left leg\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Artery name=\"Common Iliac\"     id=\"0\"  startRadius=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"External Iliac\"   id=\"1\"  startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Internal Iliac\"   id=\"2\"  startRadius=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Femoral\"          id=\"3\"  startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Popliteal\"        id=\"4\"  startRadius=\"0.06\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Anterior Tibial\"  id=\"5\"  startRadius=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Posterior Tibial\" id=\"6\"  startRadius=\"0.03\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Dorsalis Pedis\"   id=\"7\"  startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Lateral Plantar\"  id=\"8\"  startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Peroneal\"         id=\"9\"  startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Medial Plantar\"   id=\"10\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Artery name=\"Plantar Arch\"     id=\"11\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Vein name=\"Common Iliac\"       id=\"12\" startRadius=\"0.1\"    length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"External Iliac\"     id=\"13\" startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Internal Iliac\"     id=\"14\" startRadius=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Femoral\"            id=\"15\" startRadius=\"0.08\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Popliteal\"          id=\"16\" startRadius=\"0.045\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Anterior Tibial\"    id=\"17\" startRadius=\"0.015\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Great Saphenous\"    id=\"18\" startRadius=\"0.025\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Small Saphenous\"    id=\"19\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Posterior Tibial\"   id=\"20\" startRadius=\"0.02\"   length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Peroneal\"           id=\"21\" startRadius=\"0.005\"  length=\"1\"/>\r\n"
    	  		+ "          <Vein name=\"Dorsal Venous Arch\" id=\"22\" startRadius=\"0.01\"   length=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <Capillaries name=\"Thight\"            id=\"23\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Anterior Leg\"      id=\"24\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Posterior Tibial\"  id=\"25\" volume=\"0.01\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Peroneal\"          id=\"26\" volume=\"0.01\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Digital\"           id=\"27\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "          <Capillaries name=\"Pelvic\"            id=\"28\" volume=\"0.02\" length=\"1\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"2\">\r\n"
    	  		+ "            <to id=\"28\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"3\">\r\n"
    	  		+ "            <to id=\"23\"/>\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"4\">\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"5\">\r\n"
    	  		+ "            <to id=\"24\"/>\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"6\">\r\n"
    	  		+ "            <to id=\"25\"/>\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"27\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"9\">\r\n"
    	  		+ "            <to id=\"26\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"10\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"11\">\r\n"
    	  		+ "            <to id=\"27\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--12 connect directly to inferior vena cava-->\r\n"
    	  		+ "          <Connection id=\"13\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"14\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"15\">\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"16\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"17\">\r\n"
    	  		+ "            <to id=\"16\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"18\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"19\">\r\n"
    	  		+ "            <to id=\"16\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"20\">\r\n"
    	  		+ "            <to id=\"16\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"21\">\r\n"
    	  		+ "            <to id=\"20\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"22\">\r\n"
    	  		+ "            <to id=\"17\"/>\r\n"
    	  		+ "            <to id=\"18\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"23\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "            <to id=\"18\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"24\">\r\n"
    	  		+ "            <to id=\"17\"/>\r\n"
    	  		+ "            <to id=\"18\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"25\">\r\n"
    	  		+ "            <to id=\"20\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"26\">\r\n"
    	  		+ "            <to id=\"19\"/>\r\n"
    	  		+ "            <to id=\"21\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"27\">\r\n"
    	  		+ "            <to id=\"19\"/>\r\n"
    	  		+ "            <to id=\"20\"/>\r\n"
    	  		+ "            <to id=\"22\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"28\">\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "\r\n"
    	  		+ "      <!--Vena cava drain-->\r\n"
    	  		+ "      <Flow id=\"10\" name=\"Vena cava drain\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Vein name=\"Superior Vena Cava\" id=\"0\" startRadius=\"1.25\" length=\"3\"/>\r\n"
    	  		+ "          <Vein name=\"Inferior Vena Cava\" id=\"1\" startRadius=\"1.25\" length=\"3\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections/>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "    </System>\r\n"
    	  		+ "\r\n"
    	  		+ "    <!--Respiratory system-->\r\n"
    	  		+ "    <System name=\"Respiratory\" id=\"1\" type=\"1\">\r\n"
    	  		+ "      <Flow name=\"Air\" id=\"0\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <Nose name=\"Nose\" id=\"0\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Pharynx\"        id=\"1\" startRadius=\"1\" endRadius=\"1\" length=\"5\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Larynx\"         id=\"2\" startRadius=\"1\" endRadius=\"1\" length=\"5\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Trachea\"        id=\"3\" startRadius=\"1\" endRadius=\"1\" length=\"5\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Left bronchi\"   id=\"4\" startRadius=\"0.7071\" endRadius=\"0.7071\" length=\"5\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Right bronchi\"  id=\"5\" startRadius=\"0.7071\"  endRadius=\"0.7071\"  length=\"5\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Superior left lobar bronchi\"  id=\"6\"  startRadius=\"0.5\" endRadius=\"0.5\" length=\"2.0\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Inferior left lobar bronchi\"  id=\"7\"  startRadius=\"0.5\" endRadius=\"0.5\" length=\"2.0\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Superior right lobar bronchi\" id=\"8\"  startRadius=\"0.408\" endRadius=\"0.408\" length=\"2.0\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Medium right lobar bronchi\"   id=\"9\"  startRadius=\"0.408\" endRadius=\"0.408\" length=\"2.0\"/>\r\n"
    	  		+ "          <AirConnectible name=\"Inferior right lobar bronchi\" id=\"10\" startRadius=\"0.408\" endRadius=\"0.408\" length=\"2.0\"/>\r\n"
    	  		+ "          <Alveoli name=\"Right superior alveoli\" id=\"11\" volume=\"400\"/>\r\n"
    	  		+ "          <Alveoli name=\"Right average alveoli\"  id=\"12\" volume=\"400\"/>\r\n"
    	  		+ "          <Alveoli name=\"Right inferior alveoli\" id=\"13\" volume=\"400\"/>\r\n"
    	  		+ "          <Alveoli name=\"Left superior alveoli\"  id=\"14\" volume=\"600\"/>\r\n"
    	  		+ "          <Alveoli name=\"Left inferior alveoli\"  id=\"15\" volume=\"600\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"2\">\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"3\">\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"4\">\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"5\">\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"6\">\r\n"
    	  		+ "            <to id=\"14\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"11\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"9\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"10\">\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "    </System>\r\n"
    	  		+ "\r\n"
    	  		+ "    <!--Digestive system-->\r\n"
    	  		+ "    <System name=\"Digestive\" id=\"2\" type=\"2\">\r\n"
    	  		+ "      <Flow name=\"Food\" id=\"0\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <DigestiveTract name=\"Pharynx\"              id=\"0\" length=\"4\"   volume=\"12\"/>\r\n"
    	  		+ "          <DigestiveTract name=\"Esophagus\"            id=\"1\" length=\"25\"  volume=\"314.16\"/>\r\n"
    	  		+ "          <StomachTract   name=\"Stomach\"              id=\"2\" length=\"1\"   volume=\"12\"/>\r\n"
    	  		+ "          <DuodenumTract  name=\"Duodenum\"             id=\"3\" length=\"2\"   volume=\"10\"/>\r\n"
    	  		+ "          <DigestiveTract name=\"Small intestine\"      id=\"4\" length=\"40\"  volume=\"5026.55\"/>\r\n"
    	  		+ "          <DigestiveTract name=\"Ascending colon\"      id=\"5\" length=\"38\"  volume=\"477.5\"/>\r\n"
    	  		+ "          <DigestiveTract name=\"Transverse colon\"     id=\"6\" length=\"36\"  volume=\"452.4\"/>\r\n"
    	  		+ "          <DigestiveTract name=\"Descending colon\"     id=\"7\" length=\"38\"  volume=\"477.5\"/>\r\n"
    	  		+ "          <DigestiveTract name=\"Sigmoid colon\"        id=\"8\" length=\"25\"  volume=\"314.16\"/>\r\n"
    	  		+ "          <RectumTract    name=\"Rectum\"               id=\"9\" length=\"10\"  volume=\"113.0\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <BiDuct           name=\"Cystic duct\"        id=\"10\"/>\r\n"
    	  		+ "          <Duct             name=\"Hepatic duct\"       id=\"11\"/>\r\n"
    	  		+ "          <DuctOverflowableJunction name=\"Bile duct junction\" id=\"12\"/>\r\n"
    	  		+ "          <Duct             name=\"Common bile duct\"   id=\"13\"/>\r\n"
    	  		+ "          <Duct             name=\"Pancreatic duct\"    id=\"14\"/>\r\n"
    	  		+ "          <DeversingDuct    name=\"Ampulla of Vater\"   id=\"15\"/>\r\n"
    	  		+ "          <InnerGallbladder name=\"Gallbladder duct\"   id=\"16\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections>\r\n"
    	  		+ "          <Connection id=\"0\">\r\n"
    	  		+ "            <to id=\"1\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"1\">\r\n"
    	  		+ "            <to id=\"2\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"2\">\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"3\">\r\n"
    	  		+ "            <to id=\"4\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"4\">\r\n"
    	  		+ "            <to id=\"5\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"5\">\r\n"
    	  		+ "            <to id=\"6\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"6\">\r\n"
    	  		+ "            <to id=\"7\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"7\">\r\n"
    	  		+ "            <to id=\"8\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"8\">\r\n"
    	  		+ "            <to id=\"9\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <!--9 empty outside the body...-->        \r\n"
    	  		+ "          <Connection id=\"10\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"11\">\r\n"
    	  		+ "            <to id=\"12\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"12\">\r\n"
    	  		+ "            <to id=\"13\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"13\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"14\">\r\n"
    	  		+ "            <to id=\"15\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"15\">\r\n"
    	  		+ "            <to id=\"3\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "          <Connection id=\"16\">\r\n"
    	  		+ "            <to id=\"10\"/>\r\n"
    	  		+ "          </Connection>\r\n"
    	  		+ "        </Connections>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "      <Flow name=\"Salivary\" id=\"1\">\r\n"
    	  		+ "        <Connectible>\r\n"
    	  		+ "          <SalivaryDuct name=\"Left parotid duct\"        id=\"0\" length=\"3\" volume=\"1\"/>\r\n"
    	  		+ "          <SalivaryDuct name=\"Left submandibular duct\"  id=\"1\" length=\"3\" volume=\"1\"/>\r\n"
    	  		+ "          <SalivaryDuct name=\"Left sublingual duct\"     id=\"2\" length=\"1\" volume=\"1\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "          <SalivaryDuct name=\"Right parotid duct\"       id=\"3\" length=\"3\" volume=\"1\"/>\r\n"
    	  		+ "          <SalivaryDuct name=\"Right submandibular duct\" id=\"4\" length=\"3\" volume=\"1\"/>\r\n"
    	  		+ "          <SalivaryDuct name=\"Right sublingual duct\"    id=\"5\" length=\"1\" volume=\"1\"/>\r\n"
    	  		+ "        </Connectible>\r\n"
    	  		+ "        <Connections/>\r\n"
    	  		+ "      </Flow>\r\n"
    	  		+ "    </System>\r\n"
    	  		+ "  </Systems>\r\n"
    	  		+ "  \r\n"
    	  		+ "  <!--Organs definition-->\r\n"
    	  		+ "  <Organs>\r\n"
    	  		+ "    <!--Circulatory system organ-->\r\n"
    	  		+ "    <Organ name=\"Heart\" id=\"0\" systemID=\"0\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "    <!-- Respiratory system organs-->\r\n"
    	  		+ "    <Organ name=\"Left lung\" id=\"0\" systemID=\"1\"/>\r\n"
    	  		+ "    \r\n"
    	  		+ "    <Organ name=\"Right lung\" id=\"1\" systemID=\"1\"/>\r\n"
    	  		+ "    \r\n"
    	  		+ "    <!--Digestive system organs-->\r\n"
    	  		+ "    <Organ name=\"Mouth\" id=\"0\" systemID=\"2\"/>\r\n"
    	  		+ "    \r\n"
    	  		+ "    <Organ name=\"Esophagus\" id=\"1\" systemID=\"2\"/>\r\n"
    	  		+ "    \r\n"
    	  		+ "    <Organ name=\"Stomach\" id=\"2\" systemID=\"2\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "    <Organ name=\"Small intestine\" id=\"3\" systemID=\"2\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "    <Organ name=\"Liver\" id=\"4\" systemID=\"2\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "    <Organ name=\"Pancreas\" id=\"5\" systemID=\"2\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "    <Organ name=\"Gallbladder\" id=\"6\" systemID=\"2\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "    <Organ name=\"Large intestine\" id=\"7\" systemID=\"2\"/>\r\n"
    	  		+ "\r\n"
    	  		+ "    <Organ name=\"Rectum\" id=\"8\" systemID=\"2\"/>\r\n"
    	  		+ "  </Organs>\r\n"
    	  		+ "\r\n"
    	  		+ "  <!--System Template\r\n"
    	  		+ "  <System name=\"\" id=\"\" type=\"\">    \r\n"
    	  		+ "    <Flow id=\"\" name=\"\">\r\n"
    	  		+ "      <Connectible>\r\n"
    	  		+ "        <TYPE name=\"\" id=\"\" [volume=\"\"] [length=\"\"] [startRadius=\"\"] [endRadius=\"\"]/>\r\n"
    	  		+ "      </Connectible>\r\n"
    	  		+ "      <Connections>\r\n"
    	  		+ "        <Connection id=\"\">\r\n"
    	  		+ "          <to id=\"\"/>\r\n"
    	  		+ "        </Connection>\r\n"
    	  		+ "      </Connections>\r\n"
    	  		+ "    </Flow>    \r\n"
    	  		+ "  </System>-->\r\n"
    	  		+ "  \r\n"
    	  		+ "  <!--Organ Template\r\n"
    	  		+ "  <Organ name=\"\" id=\"\" systemID=\"\"/>-->\r\n"
    	  		+ "</MainBody>\r\n"
    	  		+ "";
    	  
    	  JSONObject jsonObject = XML.toJSONObject(xmlString);
    	  String jsonPrettyPrintString = jsonObject.toString(PRETTY_PRINT_INDENT_FACTOR);
    	  
    	  System.out.println(jsonPrettyPrintString);
    	
    	
        if (args.length < 2)
        {
            System.out.println("Usage: java tp1.Devoir1A <fichierXML> <fichierJSON>");
            return;
        }
        
        String nomFichierXML = args[0];
        String nomFichierJSON = args[1];
        
        System.out.println("Debut de la conversion du fichier " + nomFichierXML + " vers le fichier " + nomFichierJSON);

        // Votre code de conversion devrait aller ici
        
        System.out.println("Conversion terminee.");
    }

}
